---
# tasks file for iteasy.ansible.roles.web_conf_scout
- name: Download shell script
  raw: "wget -P /tmp/ https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.web_conf_scout/refs/heads/main/file/web_conf_scout_no_color.sh"

- name: Change Permission
  raw: "chmod 755 /tmp/web_conf_scout.sh" 

- name: Execute the system information script using raw
  raw: "/tmp/web_conf_scout.sh {{ domain_name }}" 
  register: result

- name: Output the script execution result
  debug:
    msg: "{{ result.stdout.splitlines() }}"

- name: Remove the script after execution
  raw: "rm -f /tmp/web_conf_scout.sh"